`timescale 1ns / 1ps

module conv_accel_core_axi_lite_axis_stream #(
    parameter ROWS = 18,
    parameter COLS = 8,
    parameter IFM_W = 8,
    parameter WEIGHT_W = 8,
    parameter PSUM_W = 32,
    parameter IFM_FIFO_DEPTH = 1024,
    parameter IFM_FIFO_AW = 10,
    parameter WGT_FIFO_DEPTH = 64,
    parameter WGT_FIFO_AW = 6,
    parameter PSUM_FIFO_DEPTH = 1024,
    parameter PSUM_FIFO_AW = 10,
    parameter FM_W_MAX = 416,
    parameter FM_H_MAX = 416,
    parameter K_TILE = 18,
    parameter COUT_TILE = 16,
    parameter IFM_BANKS = 2,
    parameter WGT_TILE_AW = 11,
    parameter PSUM_BUF_AW = 10,
    parameter PSUM_BUF_DEPTH = 1024,
    parameter MULT_W = 16,
    parameter SHIFT_W = 4,
    parameter ZP_W = 8,
    parameter OFM_ADDR_W = 24,
    parameter OFM_FIFO_DEPTH = 1024,
    parameter OFM_FIFO_AW = 10,
    parameter HWC_CACHE_AW = 16,
    parameter HWC_CACHE_DEPTH = 65536,
    parameter HWC_CACHE_STRIPES = 4,
    parameter HWC_CACHE_USE_URAM = 1,
    parameter HWC_REPLAY_PIPELINE_ENABLE = 1,
    parameter CACHE_EXTRA_READ_LATENCY = 0,
    parameter HWC_CACHE_EXTRA_READ_LATENCY = CACHE_EXTRA_READ_LATENCY,
    parameter HWC_REPLAY_EXTRA_WAIT_CYCLES = 0,
    parameter IFM_PINGPONG_FIFO_ENABLE = 1,
    parameter AXIS_W = 64,
    parameter AXIS_KEEP_W = 8,
    parameter TAIL_CYCLES_CONFIG = 0
) (
    input  clk,
    input  rst,
    input  [8:0]  s_axi_awaddr,
    input         s_axi_awvalid,
    output        s_axi_awready,
    input  [31:0] s_axi_wdata,
    input  [3:0]  s_axi_wstrb,
    input         s_axi_wvalid,
    output        s_axi_wready,
    output [1:0]  s_axi_bresp,
    output        s_axi_bvalid,
    input         s_axi_bready,
    input  [8:0]  s_axi_araddr,
    input         s_axi_arvalid,
    output        s_axi_arready,
    output [31:0] s_axi_rdata,
    output [1:0]  s_axi_rresp,
    output        s_axi_rvalid,
    input         s_axi_rready,
    output bias_load_req,
    output weight_load_req,
    output feeder_fill_req,
    output [8:0] feeder_fill_fy,
    output [10:0] current_cout_base,
    output [13:0] current_pass_base_k,
    output bias_s_axis_tready,
    input  bias_s_axis_tvalid,
    input  [AXIS_W-1:0] bias_s_axis_tdata,
    input  [AXIS_KEEP_W-1:0] bias_s_axis_tkeep,
    input  bias_s_axis_tlast,
    output weight_s_axis_tready,
    input  weight_s_axis_tvalid,
    input  [AXIS_W-1:0] weight_s_axis_tdata,
    input  [AXIS_KEEP_W-1:0] weight_s_axis_tkeep,
    input  weight_s_axis_tlast,
    input  [8:0] ifm_line_words,
    output ifm_s_axis_tready,
    input  ifm_s_axis_tvalid,
    input  [AXIS_W-1:0] ifm_s_axis_tdata,
    input  [AXIS_KEEP_W-1:0] ifm_s_axis_tkeep,
    input  ifm_s_axis_tlast,
    output ofm_mem_wr_en,
    output [OFM_ADDR_W-1:0] ofm_mem_wr_addr,
    output [7:0] ofm_mem_wr_data,
    output [AXIS_W-1:0] ofm_m_axis_tdata,
    output [AXIS_KEEP_W-1:0] ofm_m_axis_tkeep,
    output ofm_m_axis_tvalid,
    input  ofm_m_axis_tready,
    output ofm_m_axis_tlast,
    output ofm_packet_full,
    output bias_axis_error,
    output weight_axis_error,
    output ifm_axis_error
);
    conv_accel_ps_dma_accel_0 u_netlist (
        .clk(clk), .rst(rst),
        .s_axi_awaddr(s_axi_awaddr), .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready), .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb), .s_axi_wvalid(s_axi_wvalid),
        .s_axi_wready(s_axi_wready), .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid), .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr), .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready), .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp), .s_axi_rvalid(s_axi_rvalid),
        .s_axi_rready(s_axi_rready),
        .bias_load_req(bias_load_req), .weight_load_req(weight_load_req),
        .feeder_fill_req(feeder_fill_req), .feeder_fill_fy(feeder_fill_fy),
        .current_cout_base(current_cout_base),
        .current_pass_base_k(current_pass_base_k),
        .bias_s_axis_tready(bias_s_axis_tready),
        .bias_s_axis_tvalid(bias_s_axis_tvalid),
        .bias_s_axis_tdata(bias_s_axis_tdata[63:0]),
        .bias_s_axis_tkeep(bias_s_axis_tkeep[7:0]),
        .bias_s_axis_tlast(bias_s_axis_tlast),
        .weight_s_axis_tready(weight_s_axis_tready),
        .weight_s_axis_tvalid(weight_s_axis_tvalid),
        .weight_s_axis_tdata(weight_s_axis_tdata[63:0]),
        .weight_s_axis_tkeep(weight_s_axis_tkeep[7:0]),
        .weight_s_axis_tlast(weight_s_axis_tlast),
        .ifm_line_words(ifm_line_words),
        .ifm_s_axis_tready(ifm_s_axis_tready),
        .ifm_s_axis_tvalid(ifm_s_axis_tvalid),
        .ifm_s_axis_tdata(ifm_s_axis_tdata[63:0]),
        .ifm_s_axis_tkeep(ifm_s_axis_tkeep[7:0]),
        .ifm_s_axis_tlast(ifm_s_axis_tlast),
        .ofm_mem_wr_en(ofm_mem_wr_en),
        .ofm_mem_wr_addr(ofm_mem_wr_addr[23:0]),
        .ofm_mem_wr_data(ofm_mem_wr_data),
        .ofm_m_axis_tdata(ofm_m_axis_tdata[63:0]),
        .ofm_m_axis_tkeep(ofm_m_axis_tkeep[7:0]),
        .ofm_m_axis_tvalid(ofm_m_axis_tvalid),
        .ofm_m_axis_tready(ofm_m_axis_tready),
        .ofm_m_axis_tlast(ofm_m_axis_tlast),
        .ofm_packet_full(ofm_packet_full),
        .bias_axis_error(bias_axis_error),
        .weight_axis_error(weight_axis_error),
        .ifm_axis_error(ifm_axis_error)
    );
endmodule
