`timescale 1ns / 1ps
`define TB_CONV_LAYER_TOP_MODULE tb_conv_layer_top_stream_tagged_fast_handoff
`define TB_CONV_LAYER_ENABLE_TAGGED_CONTEXT 1
`define TB_CONV_LAYER_ENABLE_WEIGHT_PRELOAD 1
`define TB_CONV_LAYER_ENABLE_FAST_CONTEXT_HANDOFF 1
`define TB_CONV_LAYER_PASS_PREFETCH_ENABLE 1'b1
`define TB_CONV_LAYER_DURING_COMPUTE_PREFETCH_ENABLE 1'b1
`define TB_CONV_LAYER_PSUM_STREAM_OVERLAP_ENABLE 1'b1
`define TB_CONV_LAYER_REQUIRE_CONTEXT_OVERLAP 0
`define TB_CONV_LAYER_REQUIRE_FAST_HANDOFF 1
`define TB_CONV_LAYER_PACKED_WEIGHT_WRITE 1
`define TB_CONV_LAYER_ROWS 18
`define TB_CONV_LAYER_COLS 4
`define TB_CONV_LAYER_FM_W 14
`define TB_CONV_LAYER_FM_H 14
`define TB_CONV_LAYER_OFM_W 12
`define TB_CONV_LAYER_OFM_H 12
`define TB_CONV_LAYER_IFM_D 256
`define TB_CONV_LAYER_IFM_AW 8
`define TB_CONV_LAYER_PSUM_D 256
`define TB_CONV_LAYER_PSUM_AW 8
`define TB_CONV_LAYER_PSUM_BUF_AW 8
`define TB_CONV_LAYER_TIMEOUT_CYCLES 30000
`define TB_CONV_LAYER_RAW_VECTOR_MODE 1'b1
`include "tb_conv_layer_top_stream.v"
