`timescale 1ns / 1ps
`define TB_CONV_LAYER_TOP_MODULE tb_conv_layer_top_stream_tagged_overlap_r18c16
`define TB_CONV_LAYER_ENABLE_TAGGED_CONTEXT 1
`define TB_CONV_LAYER_PASS_PREFETCH_ENABLE 1'b1
`define TB_CONV_LAYER_DURING_COMPUTE_PREFETCH_ENABLE 1'b1
`define TB_CONV_LAYER_PSUM_STREAM_OVERLAP_ENABLE 1'b1
`define TB_CONV_LAYER_REQUIRE_CONTEXT_OVERLAP 1
`define TB_CONV_LAYER_FORCE_COMMIT_BACKPRESSURE 1
`define TB_CONV_LAYER_ROWS 18
`define TB_CONV_LAYER_COLS 16
`define TB_CONV_LAYER_FM_W 38
`define TB_CONV_LAYER_FM_H 28
`define TB_CONV_LAYER_OFM_W 36
`define TB_CONV_LAYER_OFM_H 26
`define TB_CONV_LAYER_IFM_D 1024
`define TB_CONV_LAYER_IFM_AW 10
`define TB_CONV_LAYER_PSUM_D 256
`define TB_CONV_LAYER_PSUM_AW 8
`define TB_CONV_LAYER_PSUM_BUF_AW 10
`define TB_CONV_LAYER_TIMEOUT_CYCLES 100000
`define TB_CONV_LAYER_RAW_VECTOR_MODE 1'b1
`include "tb_conv_layer_top_stream.v"
